{
 "title": "Frontend Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Level Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(level) (rate({serverGroup=\"admin-api\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{serverGroup=\"admin-api\"} | json | line_format \"{{._timestamp}} [{{.serverGroup}}] {{.message}}\""
    }
   ]
  },
  {
   "title": "Endpoint TPS By Log",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate({serverGroup=\"admin-api\"} |= `test_cpu_task`[1m])",
     "legendFormat": "test_cpu_task"
    },
    {
     "expr": "rate({serverGroup=\"admin-api\"} |= `test_error`[1m])",
     "legendFormat": "test_error"
    },
    {
     "expr": "rate({serverGroup=\"admin-api\"} |= `test_io_task`[1m])",
     "legendFormat": "test_io_task"
    },
    {
     "expr": "rate({serverGroup=\"admin-api\"} |= `test_random_sleep`[1m])",
     "legendFormat": "test_random_sleep"
    },
    {
     "expr": "rate({serverGroup=\"admin-api\"} |= `test_random_status`[1m])",
     "legendFormat": "test_random_status"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Endpoint TPS by Metric",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nm_heimdall_http_requests_total{serverGroup=\"admin-api\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Endpoint TPS by Metric by promBundle",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_duration_seconds_count{serverGroup=\"admin-api\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Rate (R): Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{serverGroup=\"admin-api\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{serverGroup=\"admin-api\",status_code=~\"5.*\"}[5m])) by (path)",
     "legendFormat": "{{path}} 5xx res"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{serverGroup=\"admin-api\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration (D): The amount of time to process a request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{serverGroup=\"admin-api\"}[1m])) by (le, path, method))",
     "legendFormat": "p90 {{method}} {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, path, method))",
     "legendFormat": "p50 {{method}} {{path}}"
    }
   ]
  }
 ]
}